os: linux
dist: bionic
language: c

# only build master branch and PR's
branches:
  only:
    - master

services:
  - docker

script:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - make --no-builtin-rules build
  - make --no-builtin-rules test

deploy:
  provider: script
  script:
    - make push
    - curl -X POST "https://hooks.microbadger.com/images/virtualstaticvoid/heroku-docker-r/$MICROBADGE_TOKEN"
  on:
    branch: master
